name: Linting
on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  prose:
    runs-on: ubuntu-22.04 # See https://github.com/errata-ai/vale-action/issues/128 before upgrading
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip3 install -r docs/requirements.txt

    - name: Get changed files
      id: changed-files
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep '^docs/')"

    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        filter_mode: added
        version: 3.7.1
        files: ${{ steps.changed-files.outputs.files }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip3 install -r docs/requirements.txt
    
    - name: Build docs
      working-directory: docs
      run: make html

    - name: Check links
      working-directory: docs
      run: make checklinks
